#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_COMMA = 1,
  anon_sym_SLASH = 2,
  anon_sym_DASH = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_COLON = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  sym_tag_plain = 9,
  anon_sym_DQUOTE = 10,
  sym__string_content = 11,
  sym__escape_sequence = 12,
  anon_sym_LF = 13,
  sym_comment = 14,
  sym_query = 15,
  sym__query = 16,
  sym_query_and = 17,
  sym_query_or = 18,
  sym__atom = 19,
  sym_atom_tag = 20,
  sym_atom_neg = 21,
  sym_atom_any = 22,
  sym_atom_group = 23,
  sym_atom_subject = 24,
  sym_atom_relation = 25,
  sym__subject = 26,
  sym_subject_any = 27,
  sym_subject_named = 28,
  sym_subject_type_only = 29,
  sym_tag = 30,
  sym_string = 31,
  aux_sym__string_contents = 32,
  sym__newline = 33,
  aux_sym_query_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_tag_plain] = "tag_plain",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_content] = "_string_content",
  [sym__escape_sequence] = "_escape_sequence",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [sym_query] = "query",
  [sym__query] = "_query",
  [sym_query_and] = "query_and",
  [sym_query_or] = "query_or",
  [sym__atom] = "_atom",
  [sym_atom_tag] = "atom_tag",
  [sym_atom_neg] = "atom_neg",
  [sym_atom_any] = "atom_any",
  [sym_atom_group] = "atom_group",
  [sym_atom_subject] = "atom_subject",
  [sym_atom_relation] = "atom_relation",
  [sym__subject] = "_subject",
  [sym_subject_any] = "subject_any",
  [sym_subject_named] = "subject_named",
  [sym_subject_type_only] = "subject_type_only",
  [sym_tag] = "tag",
  [sym_string] = "string",
  [aux_sym__string_contents] = "_string_contents",
  [sym__newline] = "_newline",
  [aux_sym_query_repeat1] = "query_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_tag_plain] = sym_tag_plain,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_content] = sym__string_content,
  [sym__escape_sequence] = sym__escape_sequence,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [sym_query] = sym_query,
  [sym__query] = sym__query,
  [sym_query_and] = sym_query_and,
  [sym_query_or] = sym_query_or,
  [sym__atom] = sym__atom,
  [sym_atom_tag] = sym_atom_tag,
  [sym_atom_neg] = sym_atom_neg,
  [sym_atom_any] = sym_atom_any,
  [sym_atom_group] = sym_atom_group,
  [sym_atom_subject] = sym_atom_subject,
  [sym_atom_relation] = sym_atom_relation,
  [sym__subject] = sym__subject,
  [sym_subject_any] = sym_subject_any,
  [sym_subject_named] = sym_subject_named,
  [sym_subject_type_only] = sym_subject_type_only,
  [sym_tag] = sym_tag,
  [sym_string] = sym_string,
  [aux_sym__string_contents] = aux_sym__string_contents,
  [sym__newline] = sym__newline,
  [aux_sym_query_repeat1] = aux_sym_query_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_plain] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym__escape_sequence] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym__query] = {
    .visible = false,
    .named = true,
  },
  [sym_query_and] = {
    .visible = true,
    .named = true,
  },
  [sym_query_or] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_atom_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_neg] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_any] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_group] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_relation] = {
    .visible = true,
    .named = true,
  },
  [sym__subject] = {
    .visible = false,
    .named = true,
  },
  [sym_subject_any] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_named] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_type_only] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__string_contents] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_query_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 18,
        '"', 14,
        '#', 19,
        '(', 8,
        ')', 9,
        ',', 5,
        '-', 7,
        '/', 6,
        ':', 10,
        '[', 11,
        '\\', 2,
        ']', 12,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '\'' ||
          ('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 17,
        '/', 17,
        '\\', 17,
        'b', 17,
        'f', 17,
        'n', 17,
        'r', 17,
        't', 17,
        'u', 17,
      );
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 18,
        '"', 14,
        '#', 19,
        '(', 8,
        ')', 9,
        ',', 5,
        '-', 7,
        '/', 6,
        ':', 10,
        '[', 11,
        ']', 12,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '\'' ||
          ('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(13);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_tag_plain);
      if (lookahead == ' ' ||
          lookahead == '\'' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__escape_sequence);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_tag_plain] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__escape_sequence] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_query] = STATE(45),
    [sym__query] = STATE(27),
    [sym_query_and] = STATE(27),
    [sym_query_or] = STATE(27),
    [sym__atom] = STATE(27),
    [sym_atom_tag] = STATE(27),
    [sym_atom_neg] = STATE(27),
    [sym_atom_any] = STATE(27),
    [sym_atom_group] = STATE(27),
    [sym_atom_subject] = STATE(27),
    [sym_atom_relation] = STATE(27),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(9),
    [aux_sym_query_repeat1] = STATE(9),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym__query] = STATE(23),
    [sym_query_and] = STATE(23),
    [sym_query_or] = STATE(23),
    [sym__atom] = STATE(23),
    [sym_atom_tag] = STATE(23),
    [sym_atom_neg] = STATE(23),
    [sym_atom_any] = STATE(23),
    [sym_atom_group] = STATE(23),
    [sym_atom_subject] = STATE(23),
    [sym_atom_relation] = STATE(23),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(14),
    [aux_sym_query_repeat1] = STATE(14),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym__query] = STATE(23),
    [sym_query_and] = STATE(23),
    [sym_query_or] = STATE(23),
    [sym__atom] = STATE(23),
    [sym_atom_tag] = STATE(23),
    [sym_atom_neg] = STATE(23),
    [sym_atom_any] = STATE(23),
    [sym_atom_group] = STATE(23),
    [sym_atom_subject] = STATE(23),
    [sym_atom_relation] = STATE(23),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(14),
    [aux_sym_query_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym__query] = STATE(30),
    [sym_query_and] = STATE(30),
    [sym_query_or] = STATE(30),
    [sym__atom] = STATE(30),
    [sym_atom_tag] = STATE(30),
    [sym_atom_neg] = STATE(30),
    [sym_atom_any] = STATE(30),
    [sym_atom_group] = STATE(30),
    [sym_atom_subject] = STATE(30),
    [sym_atom_relation] = STATE(30),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(8),
    [aux_sym_query_repeat1] = STATE(8),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym__query] = STATE(23),
    [sym_query_and] = STATE(23),
    [sym_query_or] = STATE(23),
    [sym__atom] = STATE(23),
    [sym_atom_tag] = STATE(23),
    [sym_atom_neg] = STATE(23),
    [sym_atom_any] = STATE(23),
    [sym_atom_group] = STATE(23),
    [sym_atom_subject] = STATE(23),
    [sym_atom_relation] = STATE(23),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(14),
    [aux_sym_query_repeat1] = STATE(14),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym__query] = STATE(23),
    [sym_query_and] = STATE(23),
    [sym_query_or] = STATE(23),
    [sym__atom] = STATE(23),
    [sym_atom_tag] = STATE(23),
    [sym_atom_neg] = STATE(23),
    [sym_atom_any] = STATE(23),
    [sym_atom_group] = STATE(23),
    [sym_atom_subject] = STATE(23),
    [sym_atom_relation] = STATE(23),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(14),
    [aux_sym_query_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [7] = {
    [sym__query] = STATE(23),
    [sym_query_and] = STATE(23),
    [sym_query_or] = STATE(23),
    [sym__atom] = STATE(23),
    [sym_atom_tag] = STATE(23),
    [sym_atom_neg] = STATE(23),
    [sym_atom_any] = STATE(23),
    [sym_atom_group] = STATE(23),
    [sym_atom_subject] = STATE(23),
    [sym_atom_relation] = STATE(23),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(14),
    [aux_sym_query_repeat1] = STATE(14),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [8] = {
    [sym__query] = STATE(29),
    [sym_query_and] = STATE(29),
    [sym_query_or] = STATE(29),
    [sym__atom] = STATE(29),
    [sym_atom_tag] = STATE(29),
    [sym_atom_neg] = STATE(29),
    [sym_atom_any] = STATE(29),
    [sym_atom_group] = STATE(29),
    [sym_atom_subject] = STATE(29),
    [sym_atom_relation] = STATE(29),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(14),
    [aux_sym_query_repeat1] = STATE(14),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [9] = {
    [sym__query] = STATE(28),
    [sym_query_and] = STATE(28),
    [sym_query_or] = STATE(28),
    [sym__atom] = STATE(28),
    [sym_atom_tag] = STATE(28),
    [sym_atom_neg] = STATE(28),
    [sym_atom_any] = STATE(28),
    [sym_atom_group] = STATE(28),
    [sym_atom_subject] = STATE(28),
    [sym_atom_relation] = STATE(28),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [sym__newline] = STATE(14),
    [aux_sym_query_repeat1] = STATE(14),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [10] = {
    [sym__query] = STATE(25),
    [sym_query_and] = STATE(25),
    [sym_query_or] = STATE(25),
    [sym__atom] = STATE(25),
    [sym_atom_tag] = STATE(25),
    [sym_atom_neg] = STATE(25),
    [sym_atom_any] = STATE(25),
    [sym_atom_group] = STATE(25),
    [sym_atom_subject] = STATE(25),
    [sym_atom_relation] = STATE(25),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [11] = {
    [sym__query] = STATE(23),
    [sym_query_and] = STATE(23),
    [sym_query_or] = STATE(23),
    [sym__atom] = STATE(23),
    [sym_atom_tag] = STATE(23),
    [sym_atom_neg] = STATE(23),
    [sym_atom_any] = STATE(23),
    [sym_atom_group] = STATE(23),
    [sym_atom_subject] = STATE(23),
    [sym_atom_relation] = STATE(23),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [12] = {
    [sym__atom] = STATE(35),
    [sym_atom_tag] = STATE(35),
    [sym_atom_neg] = STATE(35),
    [sym_atom_any] = STATE(35),
    [sym_atom_group] = STATE(35),
    [sym_atom_subject] = STATE(35),
    [sym_atom_relation] = STATE(35),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [13] = {
    [sym__atom] = STATE(32),
    [sym_atom_tag] = STATE(32),
    [sym_atom_neg] = STATE(32),
    [sym_atom_any] = STATE(32),
    [sym_atom_group] = STATE(32),
    [sym_atom_subject] = STATE(32),
    [sym_atom_relation] = STATE(32),
    [sym__subject] = STATE(43),
    [sym_subject_any] = STATE(43),
    [sym_subject_named] = STATE(43),
    [sym_subject_type_only] = STATE(43),
    [sym_tag] = STATE(20),
    [sym_string] = STATE(16),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_tag_plain] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_LF,
    STATE(14), 2,
      sym__newline,
      aux_sym_query_repeat1,
    ACTIONS(31), 7,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [20] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_tag_plain,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string,
    STATE(22), 1,
      sym_tag,
    STATE(47), 4,
      sym__subject,
      sym_subject_any,
      sym_subject_named,
      sym_subject_type_only,
  [45] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LF,
  [60] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LF,
  [75] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LF,
  [90] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_tag_plain,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string,
    STATE(22), 1,
      sym_tag,
    STATE(38), 4,
      sym__subject,
      sym_subject_any,
      sym_subject_named,
      sym_subject_type_only,
  [115] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 2,
      anon_sym_DASH,
      anon_sym_COLON,
    ACTIONS(42), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LF,
  [146] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [161] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_SLASH,
    STATE(7), 2,
      sym__newline,
      aux_sym_query_repeat1,
    ACTIONS(50), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LF,
  [178] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LF,
  [191] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(7), 2,
      sym__newline,
      aux_sym_query_repeat1,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [206] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LF,
  [219] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_SLASH,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_LF,
    STATE(3), 2,
      sym__newline,
      aux_sym_query_repeat1,
  [239] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      anon_sym_SLASH,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(66), 1,
      anon_sym_LF,
    STATE(6), 2,
      sym__newline,
      aux_sym_query_repeat1,
  [259] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_RPAREN,
    ACTIONS(52), 1,
      anon_sym_SLASH,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(68), 1,
      anon_sym_LF,
    STATE(2), 2,
      sym__newline,
      aux_sym_query_repeat1,
  [279] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_SLASH,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(70), 1,
      anon_sym_RPAREN,
    ACTIONS(72), 1,
      anon_sym_LF,
    STATE(5), 2,
      sym__newline,
      aux_sym_query_repeat1,
  [299] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_tag_plain,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_string,
    STATE(44), 1,
      sym_tag,
  [318] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [373] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_LF,
  [395] = 4,
    ACTIONS(90), 1,
      anon_sym_DQUOTE,
    ACTIONS(94), 1,
      sym_comment,
    STATE(42), 1,
      aux_sym__string_contents,
    ACTIONS(92), 2,
      sym__string_content,
      sym__escape_sequence,
  [409] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_tag_plain,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string,
    STATE(46), 1,
      sym_tag,
  [425] = 4,
    ACTIONS(94), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym__string_contents,
    ACTIONS(98), 2,
      sym__string_content,
      sym__escape_sequence,
  [439] = 4,
    ACTIONS(94), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym__string_contents,
    ACTIONS(102), 2,
      sym__string_content,
      sym__escape_sequence,
  [453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_DASH,
    ACTIONS(107), 1,
      anon_sym_COLON,
  [463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
  [470] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
  [477] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_RBRACK,
  [484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_DASH,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 20,
  [SMALL_STATE(16)] = 45,
  [SMALL_STATE(17)] = 60,
  [SMALL_STATE(18)] = 75,
  [SMALL_STATE(19)] = 90,
  [SMALL_STATE(20)] = 115,
  [SMALL_STATE(21)] = 133,
  [SMALL_STATE(22)] = 146,
  [SMALL_STATE(23)] = 161,
  [SMALL_STATE(24)] = 178,
  [SMALL_STATE(25)] = 191,
  [SMALL_STATE(26)] = 206,
  [SMALL_STATE(27)] = 219,
  [SMALL_STATE(28)] = 239,
  [SMALL_STATE(29)] = 259,
  [SMALL_STATE(30)] = 279,
  [SMALL_STATE(31)] = 299,
  [SMALL_STATE(32)] = 318,
  [SMALL_STATE(33)] = 329,
  [SMALL_STATE(34)] = 340,
  [SMALL_STATE(35)] = 351,
  [SMALL_STATE(36)] = 362,
  [SMALL_STATE(37)] = 373,
  [SMALL_STATE(38)] = 384,
  [SMALL_STATE(39)] = 395,
  [SMALL_STATE(40)] = 409,
  [SMALL_STATE(41)] = 425,
  [SMALL_STATE(42)] = 439,
  [SMALL_STATE(43)] = 453,
  [SMALL_STATE(44)] = 463,
  [SMALL_STATE(45)] = 470,
  [SMALL_STATE(46)] = 477,
  [SMALL_STATE(47)] = 484,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_tag, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_type_only, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_named, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_and, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_any, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_or, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_named, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_neg, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_group, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_any, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_subject, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_group, 4, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_group, 5, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_relation, 5, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_contents, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__string_contents, 2, 0, 0), SHIFT_REPEAT(42),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [111] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_novi_query(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
