#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 49

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_AT = 3,
  anon_sym_DOT = 4,
  anon_sym_GT = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_COLON = 8,
  anon_sym_COMMA = 9,
  anon_sym_SLASH = 10,
  anon_sym_DASH = 11,
  sym_tag_plain = 12,
  anon_sym_DQUOTE = 13,
  sym__string_content = 14,
  sym__escape_sequence = 15,
  anon_sym_LF = 16,
  sym_comment = 17,
  sym_body = 18,
  sym_subject_ref = 19,
  sym_subject = 20,
  sym__tags = 21,
  sym_tag_and = 22,
  sym_tag_or = 23,
  sym_tag_group = 24,
  sym_tag_neg = 25,
  sym_tag = 26,
  sym_string = 27,
  aux_sym__string_contents = 28,
  sym__newline = 29,
  aux_sym_body_repeat1 = 30,
  aux_sym_body_repeat2 = 31,
  aux_sym_subject_ref_repeat1 = 32,
  aux_sym_tag_group_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT] = "@",
  [anon_sym_DOT] = ".",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [sym_tag_plain] = "tag_plain",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_content] = "_string_content",
  [sym__escape_sequence] = "_escape_sequence",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [sym_body] = "body",
  [sym_subject_ref] = "subject_ref",
  [sym_subject] = "subject",
  [sym__tags] = "_tags",
  [sym_tag_and] = "tag_and",
  [sym_tag_or] = "tag_or",
  [sym_tag_group] = "tag_group",
  [sym_tag_neg] = "tag_neg",
  [sym_tag] = "tag",
  [sym_string] = "string",
  [aux_sym__string_contents] = "_string_contents",
  [sym__newline] = "_newline",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_body_repeat2] = "body_repeat2",
  [aux_sym_subject_ref_repeat1] = "subject_ref_repeat1",
  [aux_sym_tag_group_repeat1] = "tag_group_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_tag_plain] = sym_tag_plain,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_content] = sym__string_content,
  [sym__escape_sequence] = sym__escape_sequence,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [sym_body] = sym_body,
  [sym_subject_ref] = sym_subject_ref,
  [sym_subject] = sym_subject,
  [sym__tags] = sym__tags,
  [sym_tag_and] = sym_tag_and,
  [sym_tag_or] = sym_tag_or,
  [sym_tag_group] = sym_tag_group,
  [sym_tag_neg] = sym_tag_neg,
  [sym_tag] = sym_tag,
  [sym_string] = sym_string,
  [aux_sym__string_contents] = aux_sym__string_contents,
  [sym__newline] = sym__newline,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_body_repeat2] = aux_sym_body_repeat2,
  [aux_sym_subject_ref_repeat1] = aux_sym_subject_ref_repeat1,
  [aux_sym_tag_group_repeat1] = aux_sym_tag_group_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_plain] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym__escape_sequence] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym__tags] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_and] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_or] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_group] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_neg] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__string_contents] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_ref_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_group_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_context = 2,
  field_identities = 3,
  field_name = 4,
  field_relation = 5,
  field_subject = 6,
  field_tags = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_context] = "context",
  [field_identities] = "identities",
  [field_name] = "name",
  [field_relation] = "relation",
  [field_subject] = "subject",
  [field_tags] = "tags",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 3},
  [10] = {.index = 20, .length = 3},
  [11] = {.index = 23, .length = 3},
  [12] = {.index = 26, .length = 3},
  [13] = {.index = 29, .length = 3},
  [14] = {.index = 32, .length = 3},
  [15] = {.index = 35, .length = 3},
  [16] = {.index = 38, .length = 4},
  [17] = {.index = 42, .length = 3},
  [18] = {.index = 45, .length = 4},
  [19] = {.index = 49, .length = 4},
  [20] = {.index = 53, .length = 4},
  [21] = {.index = 57, .length = 4},
  [22] = {.index = 61, .length = 4},
  [23] = {.index = 65, .length = 4},
  [24] = {.index = 69, .length = 3},
  [25] = {.index = 72, .length = 4},
  [26] = {.index = 76, .length = 4},
  [27] = {.index = 80, .length = 4},
  [28] = {.index = 84, .length = 5},
  [29] = {.index = 89, .length = 5},
  [30] = {.index = 94, .length = 4},
  [31] = {.index = 98, .length = 4},
  [32] = {.index = 102, .length = 5},
  [33] = {.index = 107, .length = 4},
  [34] = {.index = 111, .length = 5},
  [35] = {.index = 116, .length = 5},
  [36] = {.index = 121, .length = 4},
  [37] = {.index = 125, .length = 5},
  [38] = {.index = 130, .length = 5},
  [39] = {.index = 135, .length = 5},
  [40] = {.index = 140, .length = 6},
  [41] = {.index = 146, .length = 5},
  [42] = {.index = 151, .length = 5},
  [43] = {.index = 156, .length = 5},
  [44] = {.index = 161, .length = 6},
  [45] = {.index = 167, .length = 6},
  [46] = {.index = 173, .length = 6},
  [47] = {.index = 179, .length = 6},
  [48] = {.index = 185, .length = 7},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_subject, 0},
  [1] =
    {field_body, 1},
    {field_subject, 0},
  [3] =
    {field_name, 1},
    {field_subject, 0},
  [5] =
    {field_identities, 1},
    {field_subject, 0},
  [7] =
    {field_relation, 2},
    {field_subject, 0},
  [9] =
    {field_subject, 0},
    {field_tags, 2},
  [11] =
    {field_body, 2},
    {field_name, 1},
    {field_subject, 0},
  [14] =
    {field_body, 2},
    {field_identities, 1},
    {field_subject, 0},
  [17] =
    {field_identities, 1},
    {field_name, 2},
    {field_subject, 0},
  [20] =
    {field_body, 3},
    {field_relation, 2},
    {field_subject, 0},
  [23] =
    {field_body, 3},
    {field_subject, 0},
    {field_tags, 2},
  [26] =
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
  [29] =
    {field_name, 1},
    {field_subject, 0},
    {field_tags, 3},
  [32] =
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
  [35] =
    {field_identities, 1},
    {field_subject, 0},
    {field_tags, 3},
  [38] =
    {field_body, 3},
    {field_identities, 1},
    {field_name, 2},
    {field_subject, 0},
  [42] =
    {field_relation, 2},
    {field_subject, 0},
    {field_tags, 4},
  [45] =
    {field_body, 4},
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
  [49] =
    {field_body, 4},
    {field_name, 1},
    {field_subject, 0},
    {field_tags, 3},
  [53] =
    {field_body, 4},
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
  [57] =
    {field_body, 4},
    {field_identities, 1},
    {field_subject, 0},
    {field_tags, 3},
  [61] =
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
  [65] =
    {field_identities, 1},
    {field_name, 2},
    {field_subject, 0},
    {field_tags, 4},
  [69] =
    {field_context, 4},
    {field_relation, 2},
    {field_subject, 0},
  [72] =
    {field_body, 5},
    {field_relation, 2},
    {field_subject, 0},
    {field_tags, 4},
  [76] =
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 5},
  [80] =
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 5},
  [84] =
    {field_body, 5},
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
  [89] =
    {field_body, 5},
    {field_identities, 1},
    {field_name, 2},
    {field_subject, 0},
    {field_tags, 4},
  [94] =
    {field_body, 6},
    {field_context, 4},
    {field_relation, 2},
    {field_subject, 0},
  [98] =
    {field_context, 5},
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
  [102] =
    {field_body, 6},
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 5},
  [107] =
    {field_context, 5},
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
  [111] =
    {field_body, 6},
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 5},
  [116] =
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
    {field_tags, 6},
  [121] =
    {field_context, 4},
    {field_relation, 2},
    {field_subject, 0},
    {field_tags, 7},
  [125] =
    {field_body, 7},
    {field_context, 5},
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
  [130] =
    {field_body, 7},
    {field_context, 5},
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
  [135] =
    {field_context, 6},
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
  [140] =
    {field_body, 7},
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
    {field_tags, 6},
  [146] =
    {field_body, 8},
    {field_context, 4},
    {field_relation, 2},
    {field_subject, 0},
    {field_tags, 7},
  [151] =
    {field_context, 5},
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 8},
  [156] =
    {field_context, 5},
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 8},
  [161] =
    {field_body, 8},
    {field_context, 6},
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
  [167] =
    {field_body, 9},
    {field_context, 5},
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 8},
  [173] =
    {field_body, 9},
    {field_context, 5},
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 8},
  [179] =
    {field_context, 6},
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
    {field_tags, 9},
  [185] =
    {field_body, 10},
    {field_context, 6},
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
    {field_tags, 9},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 21,
        '"', 17,
        '#', 22,
        '(', 10,
        ')', 11,
        ',', 13,
        '-', 15,
        '.', 8,
        '/', 14,
        ':', 12,
        '>', 9,
        '@', 7,
        '\\', 2,
        '{', 5,
        '}', 6,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 20,
        '/', 20,
        '\\', 20,
        'b', 20,
        'f', 20,
        'n', 20,
        'r', 20,
        't', 20,
        'u', 20,
      );
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 21,
        '"', 17,
        '#', 22,
        '(', 10,
        ')', 11,
        ',', 13,
        '-', 15,
        '.', 8,
        '/', 14,
        ':', 12,
        '>', 9,
        '@', 7,
        '{', 5,
        '}', 6,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(16);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_tag_plain);
      if (lookahead == ' ' ||
          lookahead == '\'' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__escape_sequence);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_tag_plain] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__escape_sequence] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_body] = STATE(109),
    [anon_sym_LBRACE] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_RPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LF,
    STATE(4), 1,
      sym_string,
    STATE(9), 1,
      aux_sym_tag_group_repeat1,
    STATE(3), 2,
      sym__newline,
      aux_sym_body_repeat1,
    STATE(38), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [40] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 1,
      anon_sym_LF,
    STATE(4), 1,
      sym_string,
    STATE(10), 1,
      aux_sym_tag_group_repeat1,
    STATE(40), 2,
      sym__newline,
      aux_sym_body_repeat1,
    STATE(38), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [80] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 14,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [100] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 14,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [120] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 14,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 13,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 13,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [178] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    STATE(4), 1,
      sym_string,
    STATE(12), 1,
      aux_sym_tag_group_repeat1,
    STATE(38), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [211] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    STATE(4), 1,
      sym_string,
    STATE(12), 1,
      aux_sym_tag_group_repeat1,
    STATE(38), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 13,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [263] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_tag_plain,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(12), 1,
      aux_sym_tag_group_repeat1,
    STATE(38), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [296] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_AT,
    ACTIONS(55), 1,
      anon_sym_GT,
    ACTIONS(57), 1,
      anon_sym_COLON,
    STATE(34), 1,
      sym_tag_group,
    STATE(52), 1,
      sym_subject_ref,
    STATE(96), 1,
      sym_body,
    ACTIONS(51), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [330] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(43), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [357] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(46), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [384] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_DOT,
    STATE(19), 1,
      aux_sym_subject_ref_repeat1,
    ACTIONS(59), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [405] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(51), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [432] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(53), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [459] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_DOT,
    STATE(24), 1,
      aux_sym_subject_ref_repeat1,
    ACTIONS(63), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [480] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(42), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [507] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(36), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [534] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(37), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [561] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(59), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [588] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DOT,
    STATE(24), 1,
      aux_sym_subject_ref_repeat1,
    ACTIONS(65), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [609] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(41), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [636] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(54), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [663] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(32), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [690] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(48), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [717] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(49), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [744] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(55), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [771] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(57), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [798] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    ACTIONS(70), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [818] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(61), 1,
      aux_sym_body_repeat2,
    STATE(67), 1,
      sym_subject,
    STATE(40), 2,
      sym__newline,
      aux_sym_body_repeat1,
  [850] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      anon_sym_AT,
    ACTIONS(80), 1,
      anon_sym_GT,
    ACTIONS(82), 1,
      anon_sym_COLON,
    STATE(44), 1,
      sym_subject_ref,
    STATE(87), 1,
      sym_body,
    ACTIONS(78), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [878] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    ACTIONS(86), 1,
      anon_sym_LF,
    STATE(4), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(60), 1,
      aux_sym_body_repeat2,
    STATE(67), 1,
      sym_subject,
    STATE(33), 2,
      sym__newline,
      aux_sym_body_repeat1,
  [910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [926] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    ACTIONS(90), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [944] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    ACTIONS(94), 1,
      anon_sym_LF,
    STATE(45), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(92), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [968] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [984] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LF,
    STATE(40), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(96), 6,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [1003] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(98), 1,
      sym_body,
    ACTIONS(101), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1025] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(80), 1,
      sym_body,
    ACTIONS(103), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1047] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(78), 1,
      sym_body,
    ACTIONS(105), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1069] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(109), 1,
      anon_sym_GT,
    ACTIONS(111), 1,
      anon_sym_COLON,
    STATE(90), 1,
      sym_body,
    ACTIONS(107), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1091] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LF,
    STATE(40), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(40), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [1109] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(81), 1,
      sym_body,
    ACTIONS(113), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1131] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_COLON,
    STATE(72), 1,
      sym_body,
    ACTIONS(115), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1153] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(100), 1,
      sym_body,
    ACTIONS(121), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1175] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(86), 1,
      sym_body,
    ACTIONS(123), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1197] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      anon_sym_COLON,
    STATE(88), 1,
      sym_body,
    ACTIONS(125), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1219] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(92), 1,
      sym_body,
    ACTIONS(131), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1241] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(135), 1,
      anon_sym_GT,
    ACTIONS(137), 1,
      anon_sym_COLON,
    STATE(82), 1,
      sym_body,
    ACTIONS(133), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1263] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(75), 1,
      sym_body,
    ACTIONS(139), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1285] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(93), 1,
      sym_body,
    ACTIONS(141), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1307] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(94), 1,
      sym_body,
    ACTIONS(143), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1329] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(147), 1,
      anon_sym_LPAREN,
    ACTIONS(149), 1,
      anon_sym_COLON,
    STATE(74), 1,
      sym_body,
    ACTIONS(145), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1351] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(99), 1,
      sym_body,
    ACTIONS(151), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1373] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(155), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      anon_sym_COLON,
    STATE(84), 1,
      sym_body,
    ACTIONS(153), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1395] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(73), 1,
      sym_body,
    ACTIONS(159), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1417] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(62), 1,
      aux_sym_body_repeat2,
    STATE(67), 1,
      sym_subject,
  [1442] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(62), 1,
      aux_sym_body_repeat2,
    STATE(67), 1,
      sym_subject,
  [1467] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    ACTIONS(165), 1,
      sym_tag_plain,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(62), 1,
      aux_sym_body_repeat2,
    STATE(67), 1,
      sym_subject,
  [1492] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(173), 1,
      anon_sym_COLON,
    STATE(83), 1,
      sym_body,
    ACTIONS(171), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1511] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(177), 1,
      anon_sym_COLON,
    STATE(89), 1,
      sym_body,
    ACTIONS(175), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1530] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      anon_sym_COLON,
    STATE(91), 1,
      sym_body,
    ACTIONS(179), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1549] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_COLON,
    STATE(97), 1,
      sym_body,
    ACTIONS(183), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1568] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LF,
    STATE(68), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(187), 3,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [1584] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LF,
    STATE(40), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(163), 3,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [1600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1643] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1663] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1673] = 4,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    ACTIONS(209), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym__string_contents,
    ACTIONS(207), 2,
      sym__string_content,
      sym__escape_sequence,
  [1687] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(16), 1,
      sym_tag,
  [1703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1713] = 4,
    ACTIONS(209), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_DQUOTE,
    STATE(76), 1,
      aux_sym__string_contents,
    ACTIONS(215), 2,
      sym__string_content,
      sym__escape_sequence,
  [1727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1747] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1757] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1767] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1777] = 4,
    ACTIONS(209), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    STATE(85), 1,
      aux_sym__string_contents,
    ACTIONS(229), 2,
      sym__string_content,
      sym__escape_sequence,
  [1791] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1811] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1821] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1861] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1881] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
    STATE(39), 1,
      sym_tag,
  [1897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1917] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1947] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(113), 1,
      sym_subject_ref,
  [1957] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(56), 1,
      sym_subject_ref,
  [1967] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(58), 1,
      sym_subject_ref,
  [1977] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(112), 1,
      sym_subject_ref,
  [1987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(110), 1,
      sym_subject_ref,
  [1997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(111), 1,
      sym_subject_ref,
  [2007] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(47), 1,
      sym_subject_ref,
  [2017] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(50), 1,
      sym_subject_ref,
  [2027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
  [2034] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
  [2041] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
  [2048] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
  [2055] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 100,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 159,
  [SMALL_STATE(9)] = 178,
  [SMALL_STATE(10)] = 211,
  [SMALL_STATE(11)] = 244,
  [SMALL_STATE(12)] = 263,
  [SMALL_STATE(13)] = 296,
  [SMALL_STATE(14)] = 330,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 384,
  [SMALL_STATE(17)] = 405,
  [SMALL_STATE(18)] = 432,
  [SMALL_STATE(19)] = 459,
  [SMALL_STATE(20)] = 480,
  [SMALL_STATE(21)] = 507,
  [SMALL_STATE(22)] = 534,
  [SMALL_STATE(23)] = 561,
  [SMALL_STATE(24)] = 588,
  [SMALL_STATE(25)] = 609,
  [SMALL_STATE(26)] = 636,
  [SMALL_STATE(27)] = 663,
  [SMALL_STATE(28)] = 690,
  [SMALL_STATE(29)] = 717,
  [SMALL_STATE(30)] = 744,
  [SMALL_STATE(31)] = 771,
  [SMALL_STATE(32)] = 798,
  [SMALL_STATE(33)] = 818,
  [SMALL_STATE(34)] = 850,
  [SMALL_STATE(35)] = 878,
  [SMALL_STATE(36)] = 910,
  [SMALL_STATE(37)] = 926,
  [SMALL_STATE(38)] = 944,
  [SMALL_STATE(39)] = 968,
  [SMALL_STATE(40)] = 984,
  [SMALL_STATE(41)] = 1003,
  [SMALL_STATE(42)] = 1025,
  [SMALL_STATE(43)] = 1047,
  [SMALL_STATE(44)] = 1069,
  [SMALL_STATE(45)] = 1091,
  [SMALL_STATE(46)] = 1109,
  [SMALL_STATE(47)] = 1131,
  [SMALL_STATE(48)] = 1153,
  [SMALL_STATE(49)] = 1175,
  [SMALL_STATE(50)] = 1197,
  [SMALL_STATE(51)] = 1219,
  [SMALL_STATE(52)] = 1241,
  [SMALL_STATE(53)] = 1263,
  [SMALL_STATE(54)] = 1285,
  [SMALL_STATE(55)] = 1307,
  [SMALL_STATE(56)] = 1329,
  [SMALL_STATE(57)] = 1351,
  [SMALL_STATE(58)] = 1373,
  [SMALL_STATE(59)] = 1395,
  [SMALL_STATE(60)] = 1417,
  [SMALL_STATE(61)] = 1442,
  [SMALL_STATE(62)] = 1467,
  [SMALL_STATE(63)] = 1492,
  [SMALL_STATE(64)] = 1511,
  [SMALL_STATE(65)] = 1530,
  [SMALL_STATE(66)] = 1549,
  [SMALL_STATE(67)] = 1568,
  [SMALL_STATE(68)] = 1584,
  [SMALL_STATE(69)] = 1600,
  [SMALL_STATE(70)] = 1611,
  [SMALL_STATE(71)] = 1622,
  [SMALL_STATE(72)] = 1633,
  [SMALL_STATE(73)] = 1643,
  [SMALL_STATE(74)] = 1653,
  [SMALL_STATE(75)] = 1663,
  [SMALL_STATE(76)] = 1673,
  [SMALL_STATE(77)] = 1687,
  [SMALL_STATE(78)] = 1703,
  [SMALL_STATE(79)] = 1713,
  [SMALL_STATE(80)] = 1727,
  [SMALL_STATE(81)] = 1737,
  [SMALL_STATE(82)] = 1747,
  [SMALL_STATE(83)] = 1757,
  [SMALL_STATE(84)] = 1767,
  [SMALL_STATE(85)] = 1777,
  [SMALL_STATE(86)] = 1791,
  [SMALL_STATE(87)] = 1801,
  [SMALL_STATE(88)] = 1811,
  [SMALL_STATE(89)] = 1821,
  [SMALL_STATE(90)] = 1831,
  [SMALL_STATE(91)] = 1841,
  [SMALL_STATE(92)] = 1851,
  [SMALL_STATE(93)] = 1861,
  [SMALL_STATE(94)] = 1871,
  [SMALL_STATE(95)] = 1881,
  [SMALL_STATE(96)] = 1897,
  [SMALL_STATE(97)] = 1907,
  [SMALL_STATE(98)] = 1917,
  [SMALL_STATE(99)] = 1927,
  [SMALL_STATE(100)] = 1937,
  [SMALL_STATE(101)] = 1947,
  [SMALL_STATE(102)] = 1957,
  [SMALL_STATE(103)] = 1967,
  [SMALL_STATE(104)] = 1977,
  [SMALL_STATE(105)] = 1987,
  [SMALL_STATE(106)] = 1997,
  [SMALL_STATE(107)] = 2007,
  [SMALL_STATE(108)] = 2017,
  [SMALL_STATE(109)] = 2027,
  [SMALL_STATE(110)] = 2034,
  [SMALL_STATE(111)] = 2041,
  [SMALL_STATE(112)] = 2048,
  [SMALL_STATE(113)] = 2055,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_group, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_group, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_group, 4, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_ref, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_ref, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_ref_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_ref_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_neg, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_or, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_and, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 9, 0, 42),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 6),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 17),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 9),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 23),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 22),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 26),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 27),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 12),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 13),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2, 0, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 15),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 35),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 8, 0, 36),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 14),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 9, 0, 43),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 5),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 10, 0, 47),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat2, 2, 0, 0),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat2, 2, 0, 0), SHIFT_REPEAT(79),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 24),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 31),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 33),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 8, 0, 39),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat2, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 28),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 11, 0, 48),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 20),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 21),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 25),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 11),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 29),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 7),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 30),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 10),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_contents, 2, 0, 0),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__string_contents, 2, 0, 0), SHIFT_REPEAT(85),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 34),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 8),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 18),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 8, 0, 37),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 16),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 8, 0, 38),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 19),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 8, 0, 40),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 9, 0, 41),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2, 0, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 9, 0, 44),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 10, 0, 45),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 10, 0, 46),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 32),
  [260] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_novi_query(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
