#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 33

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_AT = 3,
  anon_sym_DOT = 4,
  anon_sym_GT = 5,
  anon_sym_COLON = 6,
  anon_sym_COMMA = 7,
  anon_sym_SLASH = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_DASH = 11,
  sym_tag_plain = 12,
  anon_sym_DQUOTE = 13,
  sym__string_content = 14,
  sym__escape_sequence = 15,
  anon_sym_LF = 16,
  sym_comment = 17,
  sym_body = 18,
  sym_subject_ref = 19,
  sym_subject = 20,
  sym__tags = 21,
  sym_tag_and = 22,
  sym_tag_or = 23,
  sym_tag_group = 24,
  sym_tag_neg = 25,
  sym_tag = 26,
  sym_string = 27,
  aux_sym__string_contents = 28,
  sym__newline = 29,
  aux_sym_body_repeat1 = 30,
  aux_sym_body_repeat2 = 31,
  aux_sym_subject_ref_repeat1 = 32,
  aux_sym_tag_group_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT] = "@",
  [anon_sym_DOT] = ".",
  [anon_sym_GT] = ">",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_SLASH] = "/",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH] = "-",
  [sym_tag_plain] = "tag_plain",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_content] = "_string_content",
  [sym__escape_sequence] = "_escape_sequence",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [sym_body] = "body",
  [sym_subject_ref] = "subject_ref",
  [sym_subject] = "subject",
  [sym__tags] = "_tags",
  [sym_tag_and] = "tag_and",
  [sym_tag_or] = "tag_or",
  [sym_tag_group] = "tag_group",
  [sym_tag_neg] = "tag_neg",
  [sym_tag] = "tag",
  [sym_string] = "string",
  [aux_sym__string_contents] = "_string_contents",
  [sym__newline] = "_newline",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_body_repeat2] = "body_repeat2",
  [aux_sym_subject_ref_repeat1] = "subject_ref_repeat1",
  [aux_sym_tag_group_repeat1] = "tag_group_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_tag_plain] = sym_tag_plain,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_content] = sym__string_content,
  [sym__escape_sequence] = sym__escape_sequence,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [sym_body] = sym_body,
  [sym_subject_ref] = sym_subject_ref,
  [sym_subject] = sym_subject,
  [sym__tags] = sym__tags,
  [sym_tag_and] = sym_tag_and,
  [sym_tag_or] = sym_tag_or,
  [sym_tag_group] = sym_tag_group,
  [sym_tag_neg] = sym_tag_neg,
  [sym_tag] = sym_tag,
  [sym_string] = sym_string,
  [aux_sym__string_contents] = aux_sym__string_contents,
  [sym__newline] = sym__newline,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_body_repeat2] = aux_sym_body_repeat2,
  [aux_sym_subject_ref_repeat1] = aux_sym_subject_ref_repeat1,
  [aux_sym_tag_group_repeat1] = aux_sym_tag_group_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_plain] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym__escape_sequence] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_subject_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym__tags] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_and] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_or] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_group] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_neg] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__string_contents] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_ref_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_group_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_identities = 2,
  field_name = 3,
  field_relation = 4,
  field_subject = 5,
  field_tags = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_identities] = "identities",
  [field_name] = "name",
  [field_relation] = "relation",
  [field_subject] = "subject",
  [field_tags] = "tags",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 3},
  [10] = {.index = 20, .length = 3},
  [11] = {.index = 23, .length = 3},
  [12] = {.index = 26, .length = 3},
  [13] = {.index = 29, .length = 3},
  [14] = {.index = 32, .length = 3},
  [15] = {.index = 35, .length = 3},
  [16] = {.index = 38, .length = 4},
  [17] = {.index = 42, .length = 3},
  [18] = {.index = 45, .length = 4},
  [19] = {.index = 49, .length = 4},
  [20] = {.index = 53, .length = 4},
  [21] = {.index = 57, .length = 4},
  [22] = {.index = 61, .length = 4},
  [23] = {.index = 65, .length = 4},
  [24] = {.index = 69, .length = 4},
  [25] = {.index = 73, .length = 4},
  [26] = {.index = 77, .length = 4},
  [27] = {.index = 81, .length = 5},
  [28] = {.index = 86, .length = 5},
  [29] = {.index = 91, .length = 5},
  [30] = {.index = 96, .length = 5},
  [31] = {.index = 101, .length = 5},
  [32] = {.index = 106, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_subject, 0},
  [1] =
    {field_body, 1},
    {field_subject, 0},
  [3] =
    {field_name, 1},
    {field_subject, 0},
  [5] =
    {field_identities, 1},
    {field_subject, 0},
  [7] =
    {field_relation, 2},
    {field_subject, 0},
  [9] =
    {field_subject, 0},
    {field_tags, 2},
  [11] =
    {field_body, 2},
    {field_name, 1},
    {field_subject, 0},
  [14] =
    {field_body, 2},
    {field_identities, 1},
    {field_subject, 0},
  [17] =
    {field_identities, 1},
    {field_name, 2},
    {field_subject, 0},
  [20] =
    {field_body, 3},
    {field_relation, 2},
    {field_subject, 0},
  [23] =
    {field_body, 3},
    {field_subject, 0},
    {field_tags, 2},
  [26] =
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
  [29] =
    {field_name, 1},
    {field_subject, 0},
    {field_tags, 3},
  [32] =
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
  [35] =
    {field_identities, 1},
    {field_subject, 0},
    {field_tags, 3},
  [38] =
    {field_body, 3},
    {field_identities, 1},
    {field_name, 2},
    {field_subject, 0},
  [42] =
    {field_relation, 2},
    {field_subject, 0},
    {field_tags, 4},
  [45] =
    {field_body, 4},
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
  [49] =
    {field_body, 4},
    {field_name, 1},
    {field_subject, 0},
    {field_tags, 3},
  [53] =
    {field_body, 4},
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
  [57] =
    {field_body, 4},
    {field_identities, 1},
    {field_subject, 0},
    {field_tags, 3},
  [61] =
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
  [65] =
    {field_identities, 1},
    {field_name, 2},
    {field_subject, 0},
    {field_tags, 4},
  [69] =
    {field_body, 5},
    {field_relation, 2},
    {field_subject, 0},
    {field_tags, 4},
  [73] =
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 5},
  [77] =
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 5},
  [81] =
    {field_body, 5},
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
  [86] =
    {field_body, 5},
    {field_identities, 1},
    {field_name, 2},
    {field_subject, 0},
    {field_tags, 4},
  [91] =
    {field_body, 6},
    {field_name, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 5},
  [96] =
    {field_body, 6},
    {field_identities, 1},
    {field_relation, 3},
    {field_subject, 0},
    {field_tags, 5},
  [101] =
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
    {field_tags, 6},
  [106] =
    {field_body, 7},
    {field_identities, 1},
    {field_name, 2},
    {field_relation, 4},
    {field_subject, 0},
    {field_tags, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 21,
        '"', 17,
        '#', 22,
        '(', 13,
        ')', 14,
        ',', 11,
        '-', 15,
        '.', 8,
        '/', 12,
        ':', 10,
        '>', 9,
        '@', 7,
        '\\', 2,
        '{', 5,
        '}', 6,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 20,
        '/', 20,
        '\\', 20,
        'b', 20,
        'f', 20,
        'n', 20,
        'r', 20,
        't', 20,
        'u', 20,
      );
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 21,
        '"', 17,
        '#', 22,
        '(', 13,
        ')', 14,
        ',', 11,
        '-', 15,
        '.', 8,
        '/', 12,
        ':', 10,
        '>', 9,
        '@', 7,
        '{', 5,
        '}', 6,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(16);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_tag_plain);
      if (lookahead == ' ' ||
          lookahead == '\'' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xb7) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__escape_sequence);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_tag_plain] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__escape_sequence] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_body] = STATE(85),
    [anon_sym_LBRACE] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_RPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LF,
    STATE(6), 1,
      sym_string,
    STATE(8), 1,
      aux_sym_tag_group_repeat1,
    STATE(3), 2,
      sym__newline,
      aux_sym_body_repeat1,
    STATE(26), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [40] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 1,
      anon_sym_LF,
    STATE(6), 1,
      sym_string,
    STATE(12), 1,
      aux_sym_tag_group_repeat1,
    STATE(32), 2,
      sym__newline,
      aux_sym_body_repeat1,
    STATE(26), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [80] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 14,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [100] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 14,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [120] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 14,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 13,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [159] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      sym_string,
    STATE(11), 1,
      aux_sym_tag_group_repeat1,
    STATE(26), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [192] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 13,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 13,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [230] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_RPAREN,
    ACTIONS(40), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      sym_tag_plain,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(11), 1,
      aux_sym_tag_group_repeat1,
    STATE(26), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [263] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      sym_string,
    STATE(11), 1,
      aux_sym_tag_group_repeat1,
    STATE(26), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [296] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_AT,
    ACTIONS(55), 1,
      anon_sym_GT,
    ACTIONS(57), 1,
      anon_sym_COLON,
    STATE(31), 1,
      sym_tag_group,
    STATE(39), 1,
      sym_subject_ref,
    STATE(61), 1,
      sym_body,
    ACTIONS(51), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [330] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(42), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [357] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(30), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [384] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(37), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [411] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(38), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [438] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(41), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [465] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(29), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [492] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(44), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [519] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(28), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [546] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(45), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [573] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(46), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [600] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(47), 6,
      sym__tags,
      sym_tag_and,
      sym_tag_or,
      sym_tag_group,
      sym_tag_neg,
      sym_tag,
  [627] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(61), 1,
      anon_sym_LF,
    STATE(6), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(53), 1,
      aux_sym_body_repeat2,
    STATE(56), 1,
      sym_subject,
    STATE(27), 2,
      sym__newline,
      aux_sym_body_repeat1,
  [659] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    ACTIONS(69), 1,
      anon_sym_LF,
    STATE(36), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(67), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [683] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(54), 1,
      aux_sym_body_repeat2,
    STATE(56), 1,
      sym_subject,
    STATE(32), 2,
      sym__newline,
      aux_sym_body_repeat1,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    ACTIONS(73), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [733] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [749] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    ACTIONS(77), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [769] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      anon_sym_AT,
    ACTIONS(81), 1,
      anon_sym_GT,
    ACTIONS(83), 1,
      anon_sym_COLON,
    STATE(43), 1,
      sym_subject_ref,
    STATE(62), 1,
      sym_body,
    ACTIONS(79), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [797] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_LF,
    STATE(32), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(85), 6,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_DOT,
    STATE(35), 1,
      aux_sym_subject_ref_repeat1,
    ACTIONS(90), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COLON,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [835] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_DOT,
    STATE(34), 1,
      aux_sym_subject_ref_repeat1,
    ACTIONS(94), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COLON,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [854] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_DOT,
    STATE(34), 1,
      aux_sym_subject_ref_repeat1,
    ACTIONS(99), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COLON,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [873] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LF,
    STATE(32), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(38), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [891] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(67), 1,
      sym_body,
    ACTIONS(101), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [913] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(68), 1,
      sym_body,
    ACTIONS(103), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [935] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_GT,
    ACTIONS(109), 1,
      anon_sym_COLON,
    STATE(64), 1,
      sym_body,
    ACTIONS(105), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [957] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_GT,
      anon_sym_COLON,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [971] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(71), 1,
      sym_body,
    ACTIONS(111), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [993] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(60), 1,
      sym_body,
    ACTIONS(113), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1015] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_GT,
    ACTIONS(119), 1,
      anon_sym_COLON,
    STATE(63), 1,
      sym_body,
    ACTIONS(115), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1037] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(76), 1,
      sym_body,
    ACTIONS(121), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1059] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(77), 1,
      sym_body,
    ACTIONS(123), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1081] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(78), 1,
      sym_body,
    ACTIONS(125), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1103] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(80), 1,
      sym_body,
    ACTIONS(127), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1125] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_COLON,
    STATE(75), 1,
      sym_body,
    ACTIONS(129), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1144] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(135), 1,
      sym_tag_plain,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(49), 1,
      aux_sym_body_repeat2,
    STATE(56), 1,
      sym_subject,
  [1169] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 1,
      anon_sym_COLON,
    STATE(73), 1,
      sym_body,
    ACTIONS(141), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1188] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(147), 1,
      anon_sym_COLON,
    STATE(66), 1,
      sym_body,
    ACTIONS(145), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1207] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(151), 1,
      anon_sym_COLON,
    STATE(72), 1,
      sym_body,
    ACTIONS(149), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1226] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(49), 1,
      aux_sym_body_repeat2,
    STATE(56), 1,
      sym_subject,
  [1251] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_string,
    STATE(13), 1,
      sym_tag,
    STATE(49), 1,
      aux_sym_body_repeat2,
    STATE(56), 1,
      sym_subject,
  [1276] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LF,
    STATE(32), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(133), 3,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [1292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_LF,
    STATE(55), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(155), 3,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
  [1308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1319] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1330] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1361] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1381] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1391] = 4,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(179), 1,
      sym_comment,
    STATE(74), 1,
      aux_sym__string_contents,
    ACTIONS(177), 2,
      sym__string_content,
      sym__escape_sequence,
  [1405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1415] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1435] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(40), 1,
      sym_tag,
  [1451] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_tag_plain,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
    STATE(33), 1,
      sym_tag,
  [1467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1477] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1487] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1497] = 4,
    ACTIONS(179), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_DQUOTE,
    STATE(79), 1,
      aux_sym__string_contents,
    ACTIONS(195), 2,
      sym__string_content,
      sym__escape_sequence,
  [1511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1541] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1551] = 4,
    ACTIONS(179), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    STATE(79), 1,
      aux_sym__string_contents,
    ACTIONS(207), 2,
      sym__string_content,
      sym__escape_sequence,
  [1565] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 4,
      anon_sym_RBRACE,
      sym_tag_plain,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [1575] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(48), 1,
      sym_subject_ref,
  [1585] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(52), 1,
      sym_subject_ref,
  [1595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(50), 1,
      sym_subject_ref,
  [1605] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(51), 1,
      sym_subject_ref,
  [1615] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 100,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 159,
  [SMALL_STATE(9)] = 192,
  [SMALL_STATE(10)] = 211,
  [SMALL_STATE(11)] = 230,
  [SMALL_STATE(12)] = 263,
  [SMALL_STATE(13)] = 296,
  [SMALL_STATE(14)] = 330,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 384,
  [SMALL_STATE(17)] = 411,
  [SMALL_STATE(18)] = 438,
  [SMALL_STATE(19)] = 465,
  [SMALL_STATE(20)] = 492,
  [SMALL_STATE(21)] = 519,
  [SMALL_STATE(22)] = 546,
  [SMALL_STATE(23)] = 573,
  [SMALL_STATE(24)] = 600,
  [SMALL_STATE(25)] = 627,
  [SMALL_STATE(26)] = 659,
  [SMALL_STATE(27)] = 683,
  [SMALL_STATE(28)] = 715,
  [SMALL_STATE(29)] = 733,
  [SMALL_STATE(30)] = 749,
  [SMALL_STATE(31)] = 769,
  [SMALL_STATE(32)] = 797,
  [SMALL_STATE(33)] = 816,
  [SMALL_STATE(34)] = 835,
  [SMALL_STATE(35)] = 854,
  [SMALL_STATE(36)] = 873,
  [SMALL_STATE(37)] = 891,
  [SMALL_STATE(38)] = 913,
  [SMALL_STATE(39)] = 935,
  [SMALL_STATE(40)] = 957,
  [SMALL_STATE(41)] = 971,
  [SMALL_STATE(42)] = 993,
  [SMALL_STATE(43)] = 1015,
  [SMALL_STATE(44)] = 1037,
  [SMALL_STATE(45)] = 1059,
  [SMALL_STATE(46)] = 1081,
  [SMALL_STATE(47)] = 1103,
  [SMALL_STATE(48)] = 1125,
  [SMALL_STATE(49)] = 1144,
  [SMALL_STATE(50)] = 1169,
  [SMALL_STATE(51)] = 1188,
  [SMALL_STATE(52)] = 1207,
  [SMALL_STATE(53)] = 1226,
  [SMALL_STATE(54)] = 1251,
  [SMALL_STATE(55)] = 1276,
  [SMALL_STATE(56)] = 1292,
  [SMALL_STATE(57)] = 1308,
  [SMALL_STATE(58)] = 1319,
  [SMALL_STATE(59)] = 1330,
  [SMALL_STATE(60)] = 1341,
  [SMALL_STATE(61)] = 1351,
  [SMALL_STATE(62)] = 1361,
  [SMALL_STATE(63)] = 1371,
  [SMALL_STATE(64)] = 1381,
  [SMALL_STATE(65)] = 1391,
  [SMALL_STATE(66)] = 1405,
  [SMALL_STATE(67)] = 1415,
  [SMALL_STATE(68)] = 1425,
  [SMALL_STATE(69)] = 1435,
  [SMALL_STATE(70)] = 1451,
  [SMALL_STATE(71)] = 1467,
  [SMALL_STATE(72)] = 1477,
  [SMALL_STATE(73)] = 1487,
  [SMALL_STATE(74)] = 1497,
  [SMALL_STATE(75)] = 1511,
  [SMALL_STATE(76)] = 1521,
  [SMALL_STATE(77)] = 1531,
  [SMALL_STATE(78)] = 1541,
  [SMALL_STATE(79)] = 1551,
  [SMALL_STATE(80)] = 1565,
  [SMALL_STATE(81)] = 1575,
  [SMALL_STATE(82)] = 1585,
  [SMALL_STATE(83)] = 1595,
  [SMALL_STATE(84)] = 1605,
  [SMALL_STATE(85)] = 1615,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_group, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_group, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_group, 4, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_group_repeat1, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_and, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_or, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_neg, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_ref, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_ref_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_ref_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject_ref, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 13),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 15),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 17),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 9),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 23),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 25),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 26),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 31),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 22),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat2, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat2, 2, 0, 0), SHIFT_REPEAT(6),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat2, 2, 0, 0), SHIFT_REPEAT(65),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 5),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 12),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 14),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat2, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 11),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2, 0, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 8),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 16),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 7),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 18),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 19),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 21),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 24),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 5, 0, 20),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 10),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 27),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 6, 0, 28),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 29),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 7, 0, 30),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_contents, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__string_contents, 2, 0, 0), SHIFT_REPEAT(79),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 8, 0, 32),
  [212] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_novi_query(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
